version: "3.7"

services:
  php:
    container_name: php
    image: php
    command: "php -S 0.0.0.0:9000"
    ports: 
      - "127.0.0.1:9000:9000"
    volumes:
      - ./dist:/var/www


  proxy: 
    container_name: proxy
    image: nginx:alpine
    volumes:
      - "/$PWD/.nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - ./dist:/var/www
    ports:
      - "80:443"
    depends_on: 
      - "php"

  mysql:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
